# Generated by Django 3.2.4 on 2023-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_rating_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
