# Generated by Django 3.2.4 on 2023-07-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_alter_rating_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='item',
        ),
    ]
