# Generated by Django 3.2.4 on 2023-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_remove_rating_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
