# Generated by Django 3.2.6 on 2023-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_status',
            field=models.BooleanField(default=False),
        ),
    ]
