# Generated by Django 3.2.6 on 2023-08-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_message_link_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='nickname',
        ),
    ]
