# Generated by Django 3.2.4 on 2023-07-31 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitempayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitempayed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
