# Generated by Django 3.2.4 on 2023-07-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitempayed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitempayed',
            name='deliveryDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitempayed',
            name='designComp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cartitempayed',
            name='pickedUp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitempayed',
            name='travelling',
            field=models.BooleanField(default=False),
        ),
    ]
