# Generated by Django 3.2.4 on 2023-07-11 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('designComp', models.BooleanField(default=False)),
                ('pickedUp', models.BooleanField(default=False)),
                ('travelling', models.BooleanField(default=False)),
                ('deliveryDone', models.BooleanField(default=False)),
                ('deliveryTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
